CREATE TABLE superhero (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	real_name varchar(255) not null,
	abilities varchar(2000) not null
);

INSERT INTO superhero (name, real_name, abilities) VALUES ('Spider-Man', 'Peter Benjamin Parker', 'Peter can cling to most surfaces, has superhuman strength (able to lift 10 tons optimally) and is roughly 15 times more agile than a regular human');
INSERT INTO superhero (name, real_name, abilities) VALUES ('Hulk', 'Robert Bruce Banner', 'The Hulk possesses an incredible level of superhuman physical ability. His capacity for physical strength is potentially limitless due to the fact that the Hulk''s strength increases proportionally with his level of great emotional stress, anger in particular');
