CREATE TABLE superhero (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	real_name varchar(255) not null,
	abilities varchar(500) not null
);

INSERT INTO superhero (name, real_name, abilities) VALUES ('Spider-Man', 'Peter Benjamin Parker', 'Has all abilities of a spider');
INSERT INTO superhero (name, real_name, abilities) VALUES ('Hulk', 'Robert Bruce Banner', 'Gets super strong and super green when he is angry');
